doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
            uuid_varbinary_type: App\Others\UuidVarbinaryType
        mapping_types:
            uuid_binary_ordered_time: binary