doctrine:
    dbal:
        types:
            uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
            VARBINARY: App\Others\UuidVarbinaryType
        mapping_types:
            uuid_binary_ordered_time: VARBINARY